Add python3 support.
andravin/wincnn pull request #20
Opened 2019-06-04 18:54 UTC by cbalint13

This PR adds support for python3.

2019-06-05 04:44 UTC, andravin requested changes
Thanks for the pull request.

Looks good .. just need to add the print_tools import, and then I will test on python2 and python3.

2019-06-05 04:44 UTC, andravin commented on wincnn.py
> +from functools import reduce
We should also add this import to maintain python2 compatibility:

`from __future__ import print_function`

2019-06-05 05:50 UTC, cbalint13 commented on wincnn.py
> +from functools import reduce
done

2019-06-07 02:19 UTC, andravin commented
Works for me, will merge. Thanks!

2019-06-07 02:21 UTC, merged